stages:
  - check
  - test
  - deploy

check:
  stage: check
  rules:
    - changes:
        - composer.json
  script:
    - bash .wex/script/ciCheck.sh
    - echo "COMPOSER_PACKAGE_DIR=${CI_PROJECT_DIR}" > ../.env.symfony-composer
  artifacts:
    reports:
      dotenv: .env.skip

test:
  stage: test
  rules:
    - changes:
        - composer.json
      if: '$SKIP_BUILD != "true"'
  needs:
    - check
  script:
    - echo "ok"
  trigger:
      project: wexample/symfony-composer
      branch: master
      strategy: depend
  variables:
    COMPOSER_PACKAGE: $PROJECT_A_DIR

deploy:
  stage: deploy
  rules:
    - changes:
        - composer.json
      if: '$SKIP_BUILD != "true"'
  needs:
    - test
  script:
    - sudo mkdir tmp
    - sudo chown -R www-data:www-data tmp
    - cd tmp
    - sudo -u www-data git clone ${CI_REPOSITORY_URL} .
    - sudo -u www-data git remote add github git@github.com:wexample/symfony-api.git
    - sudo -u www-data git push github
