stages:
  - setup
  - pass

setup:
  stage: setup
  script:
    - cd /var/tmp
    - rm -rf symfony-composer-vendor
    - mkdir -p symfony-composer-vendor/wexample
    - cp -r ${CI_PROJECT_DIR} symfony-composer-vendor/wexample/symfony-api

pass:
  stage: pass
  needs:
    - setup
  trigger:
      project: wexample/symfony-composer
      branch: master
