stages:
  - check
  - setup
  - pass

check:
  stage: check
  only:
    - tags
  script:
    - wex script/exec -c=ciCheck

  artifacts:
    reports:
      dotenv: .env.skip

setup:
  stage: setup
  only:
    - tags
  rules:
    - if: '$SKIP_BUILD != "true"'
  script:
    - cd /var/tmp
    - rm -rf symfony-composer-vendor
    - mkdir -p symfony-composer-vendor/wexample
    - cp -r ${CI_PROJECT_DIR} symfony-composer-vendor/wexample/symfony-api

pass:
  stage: pass
  only:
    - tags
  rules:
    - if: '$SKIP_BUILD != "true"'
  needs:
    - setup
  trigger:
      project: wexample/symfony-composer
      branch: master
