before_script:
  - export COMPOSER_PACKAGE_3=$CI_PROJECT_DIR

variables:
  COMPOSER_PACKAGE_2: $CI_PROJECT_DIR

stages:
  - check
  - test

check:
  stage: check
#  only:
#    - tags
  script:
    - wex script/exec -c=ciCheck

  artifacts:
    reports:
      dotenv: .env.skip

test:
  stage: test
#  only:
#    - tags
  rules:
    - if: '$SKIP_BUILD != "true"'
  needs:
    - check
  trigger:
      project: wexample/symfony-composer
      branch: master
      strategy: depend
  variables:
    COMPOSER_PACKAGE: $PROJECT_A_DIR