services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    # Used to validate api urls requests arguments.
    Wexample\SymfonyApi\:
        resource: '../../{Command,Log,Security,Service,Twig}'
        tags: ['controller.service_arguments']

    Wexample\SymfonyApi\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags: ['kernel.event_subscriber']

    Wexample\SymfonyApi\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    Wexample\SymfonyApi\Normalizer\:
        resource: '../../Normalizer/*'
        tags: ['serializer.normalizer']

    Wexample\SymfonyApi\Api\Controller\Test\:
        resource: '../../Api/Controller/Test/*'
        tags: ['controller.service_arguments']